# Setup
title:               Sibylline Software
tagline:             Technology for human empowerment
description:         Trusted partners in AI development
url:                 https://sibylline.dev
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nathan Rice
  url:               #
  email:             nathan.alexander.rice@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-H63XXGRLBY
